---
- name: PMM-Server Standalone Installation
  gather_facts: false
  hosts: all
  tasks:
     - name: Transfering PMM-Server install script
       copy: src=pmm/pmm_server_install.sh dest=/tmp mode=0777

     - name: Transfering PMM-Server Configuration script
       copy: src=pmm/pmm_server_config.sh dest=/tmp mode=0777

     - name: Executing PMM Instalation script
       command: "sh /tmp/pmm_server_install.sh"
       register: cmd_install
     - debug: msg="{{ cmd_install.stdout_lines|replace('\\t',' ') }}"
     - debug: msg="{{ cmd_install.stderr_lines|replace('\\t',' ') }}"

     - name: Executing PMM Configuration script
       command: "sh /tmp/pmm_server_config.sh
       register: cmd_config
     - debug: msg="{{ cmd_config.stdout_lines|replace('\\t',' ') }}"
     - debug: msg="{{ cmd_config.stderr_lines|replace('\\t',' ') }}"

     - name: Removing - PMM install script
       file:
         path: /tmp/pmm_server_install.sh
         state: absent

     - name: Removing - PMM config script
       file:
         path: /tmp/pmm_server_config.sh
         state: absent
